### ISSUE TITLE
setContent Text prinded twice

### ISSUE THREAD

**Issue by gavr123456789** [JakeWharton/mosaic#419]
![image](https://github.com/user-attachments/assets/82437cc6-86b9-4211-915e-cb16ea207aaa)

Main.kt
```kotlin
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.setValue
import com.jakewharton.mosaic.MosaicScope
import com.jakewharton.mosaic.runMosaic
import com.jakewharton.mosaic.ui.Text
import kotlinx.coroutines.delay

suspend fun main() = runMosaic {
    setContent {
        Text("The count is: 0")
    }
}
```

motule.yaml
```yaml
product: jvm/app
dependencies:
#  - com.googlecode.lanterna:lanterna:3.1.2
  - com.jakewharton.mosaic:mosaic-runtime:0.12.0

settings:
  compose: enabled

```

In both 0.12.0 and 0.13.0 versions.  
Maybe its because of Linux.
